# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('types', models.CharField(choices=[('photo', 'photo'), ('text', 'text')], max_length=20)),
                ('photo_url', models.CharField(max_length=256)),
                ('button_label', models.CharField(max_length=20)),
                ('button_url', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
