# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dietinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('category_big', models.CharField(choices=[('photo', 'photo'), ('text', 'text')], max_length=20)),
                ('category_middle', models.CharField(choices=[('photo', 'photo'), ('text', 'text')], max_length=20)),
                ('category_small', models.CharField(choices=[('photo', 'photo'), ('text', 'text')], max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('text_date_day', models.TextField()),
                ('text_date_holiday', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='restId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.RestaurantInfo'),
        ),
    ]
