# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180525_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dietinfo',
            name='types',
            field=models.CharField(choices=[('식단', '식단'), ('운동', '운동')], max_length=20),
        ),
    ]
