# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180525_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
