# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-25 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180525_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietinfo',
            name='button_url',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='dietinfo',
            name='photo_url',
            field=models.CharField(max_length=1024),
        ),
    ]
