# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-31 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180525_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('button_name', models.TextField()),
                ('button_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('button_id',),
            },
        ),
    ]
