# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-01 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180602_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_score',
            field=models.IntegerField(default=0),
        ),
    ]
