# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-02 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_test_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTable',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
